### ISSUE TITLE
Could not download Kepler and TESS light curves

### ISSUE THREAD

**Issue by hzarei4** [alexteachey/MoonPy#1]
Hi,

I tried to download some TESS and Kepler light curves with the "MoonpyLC" function as:

`lc_object = MoonpyLC(targetID="Kepler-1625b")`

and sis not downloaded with this error:

targetID =  1625b

target_type =  planet
telescope =  kepler
downloading via kplr...
DOWNLOADING Kepler MAST file...
 
DOWNLOADING Kepler ExoFOP file...
 
DOWNLOADING K2 MAST file...
 
DOWNLOADING K2 ExoFOP file...
 
DOWNLOADING TESS MAST file...
 
DOWNLOADING TESS ExoFOP file...
 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-e17fa56b5923> in <module>
      5 '''
      6 #lc_object = MoonpyLC(targetID="TIC 204376737")
----> 7 lc_object = MoonpyLC(targetID="Kepler-1625b")

~/Work/MoonPy/moonpy.py in __init__(self, targetID, target_type, lc_times, lc_fluxes, lc_errors, lc_flags, lc_quarters, usr_dict, quarters, telescope, RA, Dec, coord_format, search_radius, lc_format, remove_flagged, sc, ffi, save_lc, load_lc, download, is_neighbor, clobber)
    392                         elif telescope.lower() == 'kepler':
    393                                 print('downloading via kplr...')
--> 394                                 mast_rowidx, mast_data, NEA_targetname = self.find_planet_row(row_known='n') ### cannot access ExoFOP for Kepler without a login.
    395                                 self.NEA_targetname = NEA_targetname
    396                                 try:

~/Work/MoonPy/moonpy.py in find_planet_row(self, row_known)
   1926                 ### KEPLER HANDLING
   1927                 elif (self.telescope.lower() == 'kepler'):
-> 1928                         mast_data = ascii.read(kep_mast_address)
   1929                         mast_columns = mast_data.columns
   1930                         try:

/usr/local/lib/python3.8/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    338         # through below to the non-guess way so that any problems result in a
    339         # more useful traceback.
--> 340         dat = _guess(table, new_kwargs, format, fast_reader)
    341         if dat is None:
    342             guess = False

/usr/local/lib/python3.8/site-packages/astropy/io/ascii/ui.py in _guess(table, read_kwargs, format, fast_reader)
    498 
    499             reader.guessing = True
--> 500             dat = reader.read(table)
    501             _read_trace.append({'kwargs': copy.deepcopy(guess_kwargs),
    502                                 'Reader': reader.__class__,

/usr/local/lib/python3.8/site-packages/astropy/io/ascii/core.py in read(self, table)
   1263 
   1264         # Get a list of the lines (rows) in the table
-> 1265         self.lines = self.inputter.get_lines(table, newline=newline)
   1266 
   1267         # Set self.data.data_lines to a slice of lines contain the data rows

/usr/local/lib/python3.8/site-packages/astropy/io/ascii/core.py in get_lines(self, table, newline)
    303             if (hasattr(table, 'read')
    304                     or ('\n' not in table + '' and '\r' not in table + '')):
--> 305                 with get_readable_fileobj(table,
    306                                           encoding=self.encoding) as fileobj:
    307                     table = fileobj.read()

/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py in __enter__(self)
    111         del self.args, self.kwds, self.func
    112         try:
--> 113             return next(self.gen)
    114         except StopIteration:
    115             raise RuntimeError("generator didn't yield") from None

/usr/local/lib/python3.8/site-packages/astropy/utils/data.py in get_readable_fileobj(name_or_obj, encoding, cache, show_progress, remote_timeout, sources, http_headers)
    250                 timeout=remote_timeout, sources=sources,
    251                 http_headers=http_headers)
--> 252         fileobj = io.FileIO(name_or_obj, 'r')
    253         if is_url and not cache:
    254             delete_fds.append(fileobj)

FileNotFoundError: [Errno 2] No such file or directory: '/home/Work/MoonPy/cumkois_mast.txt'

------------

And for the TESS light curves, it says the file "mast_cumtois.txt" did not exist.

Can you help me with that, please?

**Comment by alexteachey** [comment]
I suspect this is resulting from how `moonpydir` and `central_data_dir` are being defined in the code... they were specific to my machines. I have modified it now so that you can enter your own moonpydir and central_data_dir when first starting MoonPy. But that is a bit irritating, obviously, so you will probably want to hard code these directories in yourself. I will try to come up with a better solution.

If this does not solve your problem let me know.

**Comment by alexteachey** [comment]
Have come up with a better solution... moonpy now knows where it lives, so you shouldn't have to hard code any directories. the "Central Data" directory is created within the MoonPy directory, if it doesn't already exist. This is where light curves files go.

**Comment by hzarei4** [comment]
Thanks for your answer, Dr. Teachey!

I also copied the `moonpydir` commands from the `moonpy.py` file to the `pyluna.py` and `mp_lcfind.py` files and after some changes, it worked!

Thanks a lot!

Can I propose those changes as pull requests in the repo?

**Comment by alexteachey** [comment]
@hzarei4 honestly this is my first time handling outside contributions, so I don't really know what I'm doing here! But go ahead with whatever you want to do and I'll figure it out. Thanks.
